name: Nightly willowos rebuild

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  willowos-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Unshallow repo tags
        run: git fetch --prune --unshallow --tags

      - name: Check if build is necessary
        run: test "$(git tag --points-at HEAD)" = ""

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install make diffutils curl git rsync xorriso -y

      - name: Enable user namespaces
        run: sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0

      #- name: Build full distro and ISO
      #  run: JINX_CLEAN_WORKDIRS=yes PKGS_TO_INSTALL='*' make all

      #- name: Rename willowos.iso
      #  run: mv willowos.iso willowos-nightly-full-$(date +'%Y%m%d').iso

      - name: Build base distro and ISO
        run: JINX_CLEAN_WORKDIRS=yes make all

      - name: Rename willowos.iso
        run: mv willowos.iso willowos-nightly-base-$(date +'%Y%m%d').iso

      - name: Set TAG_DATE variable
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Tag new nightly release
        run: git tag nightly-$TAG_DATE && git push --tags

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          name: Nightly build ${{ env.TAG_DATE }}
          tag_name: nightly-${{ env.TAG_DATE }}
          body: Image of an up to date willowos nightly build.
          files: |
            willowos-nightly-*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
